### ISSUE TITLE
Revamp README

### ISSUE THREAD

**Issue by seagreen** [pkamenarsky/concur-replica#21]
The README has a lot of things it could talk about: `replica`, `concur`, the internals of `concur-replica`, how to use `concur-replica`, etc.

I propose that we make the target audience of the README haskellers who don't know much about the project yet, and use it to hook their interest.

I think an awesome tagline for that, right at the very top, would be:

> Build interactive web UIs using nothing but Haskell.

(Or something close to that)

... and then immediately mention how it doesn't need GHCJS or any other transpiler, and how it works.

I also think it would be good to put something like these caveats on the readme as well:

```
This strategy has two fundamental limitations:

+ It doesn't work if instant feedback is required (since there will always be some latency to the server)

+ It doesn't allow offline use

It also has two softer limitations:

+ It's not a good fit for animations, since it makes them into bandwidth hogs

+ It puts a heavier load on your server than a traditional stateless webapp
```

IMHO being honest up front about what a technology is bad at will paradoxically get more people interested, as they won't be waiting for unknown downsides to drop.

Then, as a separate section, we can go into `concur` a little bit. I think `concur` is awesome, but I also think it's benefit is less clear until you try it than LiveView-for-Haskell is, so I think that section should go later.

**Comment by pkamenarsky** [comment]
Great idea! I agree with your general outline, so if you already have a draft please open up a PR so we can discuss the details.
