### ISSUE TITLE
Get a flagship app online

### ISSUE THREAD

**Issue by seagreen** [pkamenarsky/concur-replica#22]
I think that will help re-assure people about latency issues. Do you have an app you could put online @pkamenarsky ?

We could also use http://unison.readvar.com/, but I'd have to get the hosting situation a little more solid first.

**Comment by pkamenarsky** [comment]
No app, unfortunately. I could probably get the TodoMVC example to look nice and shiny, but honestly, I think it's kind of boring.

I think the Unison code explorer is definitely much more interesting and solves a real problem, so let's put a link to it in the README once it's ready for public use.

**Comment by seagreen** [comment]
Sounds great, I'll try to get to that soon.

**Comment by seagreen** [comment]
Alright, it's ready to roll from a hosting perspective at least.

**Comment by seagreen** [comment]
I do: http://unison.readvar.com/
