### ISSUE TITLE
Update view for all connected clients (tabs, pages) when something changes

### ISSUE THREAD

**Issue by iokasimov** [pkamenarsky/concur-replica#35]
Imagine a collaborative editor where you need to deliver updates to all connected clients. For example, if I open two windows in browsers, the first page won't affect on the second one. Is there a way to do that? I've tried to use JS FFI, but it works only for the page where the action was invoked. Is it possible to propagate changes/actions to other connected clients?

**Comment by pkamenarsky** [comment]
I'm not familiar with your use case, but why not take advantage of the usual Haskell ecosystem, i.e. `Chan`s, `TChan`s, etc? Something like:

```
updateableWidget :: SomeState -> Chan SomeState -> Widget ()
updateableWidget st ch = do
  r <- fmap Left renderState st <|> fmap Right (liftIO $ readChan ch)

  case r of
    Left newSt -> do
      writeChan ch newSt
      updateableWidget newSt ch
    Right newSt -> updateableWidget newSt ch
```
The combinators discussed here https://github.com/pkamenarsky/concur-replica/issues/16 aim to abstract away that logic, but it's not clear whether that particular design would cover most use cases. Any concrete insights and suggestions for improvements are welcome!

**Comment by iokasimov** [comment]
Yes, I use `TChan`' and `TVar`'s. But it's not the problem...

For example, if you open two tabs and do something on the first one - should the second tab contents be updated? Does it work for you?
```haskell
updates <- newTChanIO @()

-- Do something on the first tab to change 
liftIO . atomically $ writeTChan updatesTChan ()

-- There is a component that forever listens updates from this chan
liftIO . atomically $ readTChan updatesForGraph
```

But it's not the problem for the first tab, where I'm actually do something. The problem is that the second tab that's not updated (and I need to reload it to see the changes).

**Comment by pkamenarsky** [comment]
Does this work for you?

```
shared st bcast ch = do
  r <- fmap Left (div [ onClick ] [ text (pack $ show st) ]) <|> fmap Right (liftIO (readChan ch))

  case r of
    Left _ -> do
      liftIO $ writeChan bcast (st + 1)
      shared (st + 1) bcast ch

    Right newSt -> shared newSt bcast ch

runShared :: IO ()
runShared = do
  bcast <- newChan
  Replica.runDefault 8080 "Shared" (\_ -> liftIO (dupChan bcast) >>= shared 0 bcast)
```

This will keep connected tabs in sync.

Keep in mind, this is just a `Chan`, so to get the current state when a new tab connects you'd need a `IORef` or `TVar`. This is exactly what the combinators in https://github.com/pkamenarsky/concur-replica/issues/16 aim to abstract away.

**Comment by iokasimov** [comment]
Yes, it works. I've tried to do somehting similar but with `TChan`'s, maybe it didn't work because I haven't duplicated chan in the body of `run` function. Thank you very much!
