### ISSUE TITLE
Use of CSS and custom JS

### ISSUE THREAD

**Issue by vesten** [pkamenarsky/concur-replica#36]
Could the docs and an example be enhanced to explain/show how CSS and custom JS could be injected to the served app?

**Comment by pkamenarsky** [comment]
Yep, the docs are severely lacking at the moment.

In the meantime, take a look at https://github.com/seagreen/unison-code-explorer/blob/master/src/UCE.hs for an example of how to serve a custom `index.html` together with CSS and JS.

**Comment by vesten** [comment]
Thanks for your reply. The information in the link was spot on.
