### ISSUE TITLE
Push to Hackage

### ISSUE THREAD

**Issue by timjs** [pkamenarsky/concur-replica#5]
Really interested in this package! Could you push it to Hackage so I can easily play with it? Or is there another recommended way to to try it out?

**Comment by timjs** [comment]
Tried to compile concur-replica as part of the Cabal's new [Nix style builds](https://cabal.readthedocs.io/en/latest/nix-local-build.html#specifying-the-local-packages) but got the following error:

```
[3 of 6] Compiling Concur.Replica.DOM ( src/Concur/Replica/DOM.hs, /Users/Tim/Sync/Projecten/concur-haskell-test/dist-newstyle/build/x86_64-osx/ghc-8.6.5/concur-replica-0.1.0.0/build/Concur/Replica/DOM.o )

src/Concur/Replica/DOM.hs:10:52-90: error:
    Module
    ‘Concur.Core’
    does not export
    ‘MonadSafeBlockingIO(liftSafeBlockingIO)’
   |
10 | import           Concur.Core              (Widget, MonadSafeBlockingIO(liftSafeBlockingIO), MonadUnsafeBlockingIO(liftUnsafeBlockingIO), MultiAlternative, wrapView, orr, display)
   |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Concur/Replica/DOM.hs:10:93-135: error:
    Module
    ‘Concur.Core’
    does not export
    ‘MonadUnsafeBlockingIO(liftUnsafeBlockingIO)’
   |
10 | import           Concur.Core              (Widget, MonadSafeBlockingIO(liftSafeBlockingIO), MonadUnsafeBlockingIO(liftUnsafeBlockingIO), MultiAlternative, wrapView, orr, display)
   |                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build concur-replica-0.1.0.0
```

which [indeed not part of](https://github.com/ajnsit/concur/search?q=MonadUnsafeBlockingIO&unscoped_q=MonadUnsafeBlockingIO&type=Issues) the concur-core library. Any idea?

**Comment by timjs** [comment]
Never mind, after some puzzling I found out you depend on a [pull request](https://github.com/ajnsit/concur/pull/16) of concur-core. Mad it compile with Cabal new-style and it works perfectly!

**Comment by ajnsit** [comment]
@timjs @pkamenarsky That PR is merged now. Looking forward to trying out Concur-Replica myself!

**Comment by pkamenarsky** [comment]
A quick update, `concur-replica` is in flux right now, but will be definitely publishing it to Hackage once everything stabilises a bit!
